







	





.build/uno/DallasTemperature/dependencies.d : 
	@echo Scanning dependencies of DallasTemperature
	@mkdir -p .build/uno/DallasTemperature
	@touch $@;

all : .build/uno/DallasTemperature/dependencies.d
	@true

