







	





.build/uno/DallasTemperature/dependencies.d : 
	@echo [96mScanning dependencies of DallasTemperature[0m
	@mkdir -p .build/uno/DallasTemperature
	@touch $@;

all : .build/uno/DallasTemperature/dependencies.d
	@true

